#!/data/data/com.termux/files/usr/bin/bash
# FB AUTO BOT
# UPLOADED BY K90 HACK GAME MOBILE

black='\033[1;30m'
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
purple='\033[1;35m'
cyan='\033[1;36m'
white='\033[1;37m'


echo -e $blue"   _______    ___               __  ";
echo -e $blue"FACEBOOK AUTO BOT";


echo -e $red"              UPLOADED BY K90 HACK GAME MOBILE  ";
echo -e $green" Cảm ơn đặc biệt đến: ";
echo -e $green" https://github.com/tomiashari/fb-autoreaction";
echo -e $green" https://github.com/dfmcvn/getFBtoken ";
echo -e $green" https://github.com/tro1d/bot-reaction-gettoken";
echo -e $white"\n";
sleep 1
echo "1 ) Gõ 1 nếu bạn chưa tải php";
echo "2 ) Gõ 2 nếu bạn đã tải php";
echo "99) Gõ 99 để thoát";
read -p "[Like và Subscribe nếu thấy hay..] >"  act;

if [ $act = 1 ] || [ $act = 1 ]
then
apt update -y && apt upgrade -y
pkg install -y php
clear
sleep 1
php 1.php
clear
php 2.php
sleep 2
clear
php 3.php
fi

if [ $act = 2 ] || [ $act = 2 ]
then
apt update -y && apt upgrade -y
clear
php 1.php
clear
php 2.php
sleep 2
clear
php 3.php
fi

if [ $act = 99 ] || [ $act = 99 ]
then
echo -e $red'Tôi cũng chỉ là người bình thường^^'
sleep 1
echo -e $red'Mọi sự cố gắng của bạn sẽ được đền đáp xứng đáng..'
sleep 2
echo -e $red'Cảm ơn những người đã tạo ra git này..đã được việt hóa hoàn toàn'
sleep 1
echo -e $red'Cảm ơn mọi người đã đồng hành cùng tôi để tạo ra git này'
sleep 1
echo -e $red'LUÔN HỌC HỎI NHỮNG NGƯỜI ĐI TRƯỚC..'
echo -e $cyan'Facebook của mình:'
echo -e $cyan'www.facebook.com/profile.php?id=100006002596531'
sleep 2
exit
fi
